services:
  redis:
      image: redis:7.2.4-bookworm
      container_name: redis

      command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}

      volumes:
        - ./data:/data
        - ./data/redis.conf:/var/lib/redis/data
      
      networks:
        - mired

      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.redis.entrypoints=redis"
        - "traefik.tcp.routers.redis.tls=true"
        - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

networks:
  mired:
    external: true