services:
  umtdd:
    container_name: um-tdd
    image: ms1:v1.0.0
    networks:
      - mired
    ports:
      - "5001:5000" #cambia el puerto de la aplicacion

networks:
  mired:
    driver: bridge

    #docker build -t ms:v1.0.0 .


