http:
  routers:
    traefik:
      rule: "Host(`traefik.sportiq.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "sportiq.localhost"
            sans:
              - "*.sportiq.localhost"
          - main: "sportiq.local"
            sans:
              - "*.sportiq.local"

tls:
  certificates:
    - certFile: "/etc/certs/sportiq-cert.pem"
      keyFile: "/etc/certs/sportiq-key.pem"
