services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 5432:5432
      - 6379:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./certs:/etc/certs
      - ./config/config.yml:/etc/traefik/config.yml
    networks:  
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

networks:
  mired:
    external: true